### ISSUE TITLE
which stm32 chip is used in this demo

### ISSUE THREAD

**Issue by feiyue1206** [sundw2014/u2f_stm32#1]
i want  to learn and test this demo,but i donot find which stm32 chip is used in this demo? Can anyone help me?

**Comment by sundw2014** [comment]
@feiyue1206 , I am sorry for the lack of a clear readme.
I tested this project with an __STM32F103RCT6__. For more details about the chips can be used, please refer to https://github.com/sundw2014/u2f_stm32/blob/3354cdb89b9f2b2510155fb5fbf5e7df3550a4e5/Project/CodeSourcery/Makefile#L61

I think any chip of __stm32f10x_hd__ series can be used without any modification of the code.

If you want to use an __stm32f10x_md__ chip like __STM32F103C8T6__,
please modify the Makefile
```
SUBMDL   = stm32f10x_hd
```
to
```
SUBMDL   = stm32f10x_md
```
Welcome to update your result here!

**Comment by feiyue1206** [comment]
3ks a lot
